Update project to use webpack, starter-kit @4a85bf3. Remove origami build service

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -10,40 +10,14 @@ jobs:
     steps:
       - checkout
       - run:
-          name: Backup package-lock.json
-          # This file gets modified during setup, which would break our use of
-          # it as a cache key. So we back it up to tmp first.
-          command: cp package-lock.json /tmp/
-      - restore_cache:
-          name: Restore cache (node_modules)
-          key: node_modules-{{ checksum "/tmp/package-lock.json" }}
-      - run:
           name: Install dependencies
-          # NB. this also does bower install as postinstall step
           command: npm install
-      - run:
-          name: Rebuild problematic node modules
-          command: npm rebuild
-      - save_cache:
-          name: Save cache (node_modules)
-          key: node_modules-{{ checksum "/tmp/package-lock.json" }}
-          paths:
-            - node_modules/
-      - run:
-          name: ESLint
-          command: npm run lint
       - run:
           name: Build
           command: npm run build
       - store_artifacts:
           name: Store artifacts (dist)
           path: dist/
-      - store_artifacts:
-          name: Store artifact (package-lock.json)
-          path: package-lock.json
-      - run:
-          name: General QA checks
-          command: npm run qa
       - deploy:
           name: Deploy
           command: |
@@ -58,7 +32,16 @@ jobs:
           command: |
             if [ "$PREVIEW" == "true" ]
             then
-              npm run check-accessibility:preview
+              npm run a11y:preview
             else
-              npm run check-accessibility
+              npm run a11y
+            fi
+      - run:
+          name: General QA tests
+          command: |
+            if [ $CIRCLE_BRANCH = "main" ]
+            then
+              npm run test
+            else
+              npm run test || echo "General QA tests failed. Continuing anyway"
             fi
