Remove qa step for now

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -36,12 +36,12 @@ jobs:
             else
               npm run a11y
             fi
-      - run:
-          name: General QA tests
-          command: |
-            if [ $CIRCLE_BRANCH = "main" ]
-            then
-              npm run test
-            else
-              npm run test || echo "General QA tests failed. Continuing anyway"
-            fi
+      # - run:
+      #     name: General QA tests
+      #     command: |
+      #       if [ $CIRCLE_BRANCH = "main" ]
+      #       then
+      #         npm run test
+      #       else
+      #         npm run test || echo "General QA tests failed. Continuing anyway"
+      #       fi
